package Formularios;

import ClasesImportadas.Frm_Notificacion;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 * @author Daniel Sánchez
 */

public class Frm_SeleccionD extends javax.swing.JFrame {

    // Variable para controlar el estado de los botones;
    private static boolean estadoBtnMax = true;
    
    public Frm_SeleccionD() {
        initComponents();
        JPanel[] paneles = {jPanel1, jPanel2, jPanel3, jPanel4};
        for (JPanel panel : paneles) {
            panel.setOpaque(false);
        }
        JButton[] botones = {btnSalir, btnAyuda, btnMinimizar, btnMaximizar, btnBack};
        for (JButton btn : botones) {
            btn.setBackground(new Color(10, 31, 58));
            // Para un botón simple btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseAdapter() {

                @Override
                public void mouseEntered(MouseEvent me) {
                    btn.setBackground(new Color(72, 153, 188));
                }

                @Override
                public void mouseExited(MouseEvent me) {
                    btn.setBackground(new Color(10, 31, 58));
                }
                
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        panelGradiente1 = new Clases.PanelGradiente();
        btnAyuda = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        btnMaximizar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnPuntuacion = new Clases.JButtonEspecial();
        panelGradiente2 = new Clases.PanelGradiente();
        jPanel1 = new javax.swing.JPanel();
        btnFacil = new Clases.JButtonEspecial();
        jPanel2 = new javax.swing.JPanel();
        btnMedio = new Clases.JButtonEspecial();
        jPanel3 = new javax.swing.JPanel();
        btnDificil = new Clases.JButtonEspecial();
        jPanel4 = new javax.swing.JPanel();
        btnCerrar = new Clases.JButtonEspecial();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        rootPanel.setLayout(new java.awt.BorderLayout());

        panelGradiente1.setColor1(new java.awt.Color(43, 27, 104));
        panelGradiente1.setColor2(new java.awt.Color(20, 10, 58));
        panelGradiente1.setPreferredSize(new java.awt.Dimension(500, 75));

        btnAyuda.setBackground(new java.awt.Color(10, 31, 58));
        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/IconoQuestion_50px.png"))); // NOI18N
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        btnMinimizar.setBackground(new java.awt.Color(10, 31, 58));
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/IconoMinimizarVentana_50px.png"))); // NOI18N
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        btnMaximizar.setBackground(new java.awt.Color(10, 31, 58));
        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/IconoMinimizar_50px.png"))); // NOI18N
        btnMaximizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaximizarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(10, 31, 58));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/IconoClose_50px.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnPuntuacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/PalPuntuacion_50px.png"))); // NOI18N
        btnPuntuacion.setRadio(20);
        btnPuntuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntuacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGradiente1Layout = new javax.swing.GroupLayout(panelGradiente1);
        panelGradiente1.setLayout(panelGradiente1Layout);
        panelGradiente1Layout.setHorizontalGroup(
            panelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradiente1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMaximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGradiente1Layout.setVerticalGroup(
            panelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradiente1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        rootPanel.add(panelGradiente1, java.awt.BorderLayout.PAGE_START);

        panelGradiente2.setColor1(new java.awt.Color(20, 10, 58));
        panelGradiente2.setColor2(new java.awt.Color(43, 27, 104));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFacil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/PalFacil_64px.png"))); // NOI18N
        btnFacil.setRadio(20);
        btnFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacilActionPerformed(evt);
            }
        });
        jPanel1.add(btnFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/PalMedio_64px.png"))); // NOI18N
        btnMedio.setRadio(20);
        btnMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedioActionPerformed(evt);
            }
        });
        jPanel2.add(btnMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDificil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/PalDificil_64px.png"))); // NOI18N
        btnDificil.setRadio(20);
        btnDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDificilActionPerformed(evt);
            }
        });
        jPanel3.add(btnDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/PalSalir_64px.png"))); // NOI18N
        btnCerrar.setRadio(20);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel4.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        btnBack.setBackground(new java.awt.Color(10, 31, 58));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/IconoBack_50px.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGradiente2Layout = new javax.swing.GroupLayout(panelGradiente2);
        panelGradiente2.setLayout(panelGradiente2Layout);
        panelGradiente2Layout.setHorizontalGroup(
            panelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradiente2Layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addGroup(panelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(panelGradiente2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGradiente2Layout.setVerticalGroup(
            panelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradiente2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        rootPanel.add(panelGradiente2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        String mensajeAyuda = "Escoge la dificultad para iniciar";
        Frm_Notificacion ayud = new Frm_Notificacion(this, Frm_Notificacion.Type.ALERT, Frm_Notificacion.Location.TOP_RIGHT, mensajeAyuda);
        ayud.showNotificacion();
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        //Si se usa setExtendedState vuelve al tamaño inicial
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnMaximizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaximizarActionPerformed
        if (estadoBtnMax) {
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            ImageIcon min = new ImageIcon("src\\Iconos\\IconoMaximizar_50px.png");
            btnMaximizar.setIcon(min);
            estadoBtnMax = false;
        } else {
            this.setExtendedState(JFrame.NORMAL);
            ImageIcon min = new ImageIcon("src\\Iconos\\IconoMinimizar_50px.png");
            btnMaximizar.setIcon(min);
            estadoBtnMax = true;
        }
        repaint();
    }//GEN-LAST:event_btnMaximizarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnPuntuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntuacionActionPerformed
        Frm_Puntaje puntaje = new Frm_Puntaje();
        puntaje.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPuntuacionActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Frm_Login login = new Frm_Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedioActionPerformed
        Frm_JuegoMedio juegoMedio = new Frm_JuegoMedio();
        this.dispose();
        juegoMedio.setVisible(true);
    }//GEN-LAST:event_btnMedioActionPerformed

    private void btnFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacilActionPerformed
        Frm_JuegoFacil juegoFacil = new Frm_JuegoFacil();
        this.dispose();
        juegoFacil.setVisible(true);
    }//GEN-LAST:event_btnFacilActionPerformed

    private void btnDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDificilActionPerformed
        Frm_JuegoDificil juegoDificil = new Frm_JuegoDificil();
        this.dispose();
        juegoDificil.setVisible(true);
    }//GEN-LAST:event_btnDificilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_SeleccionD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frm_SeleccionD().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBack;
    private Clases.JButtonEspecial btnCerrar;
    private Clases.JButtonEspecial btnDificil;
    private Clases.JButtonEspecial btnFacil;
    private javax.swing.JButton btnMaximizar;
    private Clases.JButtonEspecial btnMedio;
    private javax.swing.JButton btnMinimizar;
    private Clases.JButtonEspecial btnPuntuacion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private Clases.PanelGradiente panelGradiente1;
    private Clases.PanelGradiente panelGradiente2;
    private javax.swing.JPanel rootPanel;
    // End of variables declaration//GEN-END:variables
}
